# Comparisons, Masks and Boolean Logic

Sometimes we want to extract, modify, count or manipulate values in an array based on some criterion.

Boolean Masks enable us to do this.

## Comparison Operators as ufuncs

We've seen that using `+`, `-`, `*`, `/`, and others on arrays leads to element-wise operations.

NumPy also implements comparison operators such as `<` (less than) and `>` (greater than) as element-wise ufuncs. 

The result of these comparison operators is always an array with a Boolean data type.

In [4]:
x = np.array([1, 2, 3, 4, 5])

In [5]:
x < 3  # less than

array([ True,  True, False, False, False])

In [6]:
x > 3  # greater than

array([False, False, False,  True,  True])

In [7]:
x <= 3  # less than or equal

array([ True,  True,  True, False, False])

In [8]:
x >= 3  # greater than or equal

array([False, False,  True,  True,  True])

In [9]:
x != 3  # not equal

array([ True,  True, False,  True,  True])

In [10]:
x == 3  # equal

array([False, False,  True, False, False])

We can also do an element-wise comparison of two arrays:

In [11]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

These operators work on arrays of any size:

In [12]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [13]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

## Working with Boolean Arrays: Counting Entries

To count the number of `True` entries in a Boolean array, `np.count_nonzero` is useful:

In [14]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [15]:
# how many values less than 6?
np.count_nonzero(x < 6)

8

In [16]:
# Another way to get this information is using np.sum.
# False is 0
# True is 1
np.sum(x < 6)

8

In [17]:
# how many values less than 6 in each row?
np.sum(x < 6, axis=1)

array([4, 2, 2])

## Sanity checking data

If we're interested in quickly checking whether any or all the values are true, we can use (you guessed it) `np.any` or `np.all`:

In [18]:
# are there any values greater than 8?
np.any(x > 8)

True

In [19]:
# are there any values less than zero?
np.any(x < 0)

False

In [20]:
# are all values less than 10?
np.all(x < 10)

True

In [21]:
# are all values equal to 6?
np.all(x == 6)

False

In [22]:
# are all values in each row less than 8?
np.all(x < 8, axis=1)

array([ True, False,  True])

## Boolean Arrays as Masks

Masks are a powerful pattern to select particular subsets of data.

e.g how many values in our array `x` are less than 5?

In [25]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [26]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

By combining Boolean operations, masking operations, and aggregates, we can very quickly answer these sorts of questions for our dataset.